Updating control scripts

diff --git a/core-api/core-public-web/src/deb/control/postinst b/core-api/core-public-web/src/deb/control/postinst
--- a/core-api/core-public-web/src/deb/control/postinst
+++ b/core-api/core-public-web/src/deb/control/postinst
@@ -1,97 +1,130 @@
-#!/bin/bash
+#! /bin/bash
+
 set -e
 
-echo "Adding user 'glassfish'..."
-sudo adduser --home /home/glassfish --system --shell /bin/bash glassfish
+function install_glassfish_user {
+    echo "Adding user 'glassfish'..."
+    sudo adduser --home /home/glassfish --system --shell /bin/bash glassfish
 
-echo "Adding a new group for Glassfish administration..."
-sudo groupadd glassfishadm
+    echo "Adding a new group for Glassfish administration..."
+    sudo groupadd glassfishadm
 
-echo "Adding 'glassfish' user to be a Glassfish adminstrator..."
-sudo usermod -a -G glassfishadm glassfish
+    echo "Adding 'glassfish' user to be a Glassfish adminstrator..."
+    sudo usermod -a -G glassfishadm glassfish
 
+    return 0
+}
 
-echo "Removing OpenJDK if installed..."
-sudo apt-get remove openjdk-6-jre openjdk-6-jdk
+function install_java {
+    echo "Removing OpenJDK if installed..."
+    sudo apt-get remove openjdk-6-jre openjdk-6-jdk
 
-#maybe you have to execute this here first, else
-#add-apt-repository might fail
-sudo apt-get install python-software-properties
+    #maybe you have to execute this here first, else
+    #add-apt-repository might fail
+    sudo apt-get install python-software-properties
 
-#add new repository that contains sun java (see https://wiki.ubuntu.com/LucidLynx/ReleaseNotes)
-sudo add-apt-repository "deb http://archive.canonical.com/ lucid partner"
+    #add new repository that contains sun java (see https://wiki.ubuntu.com/LucidLynx/ReleaseNotes)
+    sudo add-apt-repository "deb http://archive.canonical.com/ lucid partner"
 
-#update to know about new repository
-sudo apt-get update
+    #update to know about new repository
+    sudo apt-get update
 
-#now install Sun JDK
-sudo apt-get install sun-java6-jdk  sun-java6-jre
+    #now install Sun JDK
+    sudo apt-get install sun-java6-jdk  sun-java6-jre
 
-#get rid of several automatically installed packages that are not needed anymore
-sudo apt-get autoremove
+    #get rid of several automatically installed packages that are not needed anymore
+    sudo apt-get autoremove
 
-#optional:
-#make sure environment points to a valid install if you are replacing...
-#sudo update-alternatives --config java
+    #optional:
+    #make sure environment points to a valid install if you are replacing...
+    #sudo update-alternatives --config java
 
-#check JDK by looking in the /etc/alternatives/ directory
-#cd /etc/alternatives
-#ls -lrt java*
+    #check JDK by looking in the /etc/alternatives/ directory
+    #cd /etc/alternatives
+    #ls -lrt java*
 
-#setting JAVA_HOME globally for all users (only for bash)
-#vim /etc/bash.bashrc
-#append the following line:
-#export JAVA_HOME=/usr/lib/jvm/java-6-sun
-echo "JAVA_HOME=/usr/lib/jvm/java-6-sun" >> /etc/bash.bashrc
+    #setting JAVA_HOME globally for all users (only for bash)
+    #vim /etc/bash.bashrc
+    #append the following line:
+    #export JAVA_HOME=/usr/lib/jvm/java-6-sun
+    echo "JAVA_HOME=/usr/lib/jvm/java-6-sun" >> /etc/bash.bashrc
 
-#setting JAVA_HOME for everyone (best place for setting env vars globally)
-#see https://help.ubuntu.com/community/EnvironmentVariables for details
-#vim /etc/environment
-#append the following lines:
-#JAVA_HOME=/usr/lib/jvm/java-6-sun
-#we will set this here because it might prevent problems later
-#AS_JAVA=/usr/lib/jvm/java-6-sun
-echo "JAVA_HOME=/usr/lib/jvm/java-6-sun" >> /etc/environment
-echo "AS_JAVA=/usr/lib/jvm/java-6-sun" >> /etc/environment
+    #setting JAVA_HOME for everyone (best place for setting env vars globally)
+    #see https://help.ubuntu.com/community/EnvironmentVariables for details
+    #vim /etc/environment
+    #append the following lines:
+    #JAVA_HOME=/usr/lib/jvm/java-6-sun
+    #we will set this here because it might prevent problems later
+    #AS_JAVA=/usr/lib/jvm/java-6-sun
+    echo "JAVA_HOME=/usr/lib/jvm/java-6-sun" >> /etc/environment
+    echo "AS_JAVA=/usr/lib/jvm/java-6-sun" >> /etc/environment
 
+    return 0
+}
 
-#if you dont't have "unzip" installed run this here first
-sudo apt-get install unzip
+function install_glassfish {
+    #if you dont't have "unzip" installed run this here first
+    sudo apt-get install unzip
 
-#now switch user to the glassfish user we created (see step 1)
-#sudo su glassfish
+    #now switch user to the glassfish user we created (see step 1)
+    #sudo su glassfish
 
-#change to home dir of glassfish
-cd /home/glassfish/
+    #change to home dir of glassfish
+    cd /home/glassfish/
 
-#create new directory if not already available
-sudo -u glassfish mkdir downloads
+    #create new directory if not already available
+    sudo -u glassfish mkdir downloads
 
-#go to the directory we created
-cd /home/glassfish/downloads/
+    #go to the directory we created
+    cd /home/glassfish/downloads/
 
-#download Glassfish and unzip
-sudo -u glassfish wget http://download.java.net/glassfish/3.1/release/glassfish-3.1.zip
-sudo -u glassfish unzip glassfish-3.1.zip
+    #download Glassfish and unzip
+    sudo -u glassfish wget http://download.java.net/glassfish/3.1/release/glassfish-3.1.zip
+    sudo -u glassfish unzip glassfish-3.1.zip
 
-#move the relevant content to home directory
-sudo -u glassfish mv /home/glassfish/downloads/glassfish3/* /home/glassfish/
-#if something has not been moved, then move it manually, i.e.:
-sudo -u glassfish mv /home/glassfish/downloads/glassfish3/.org.opensolaris,pkg /home/glassfish/.org.opensolaris,pkg
- 
-#exit from glassfish user
-#exit
+    #move the relevant content to home directory
+    sudo -u glassfish mv /home/glassfish/downloads/glassfish3/* /home/glassfish/
+    #if something has not been moved, then move it manually, i.e.:
+    sudo -u glassfish mv /home/glassfish/downloads/glassfish3/.org.opensolaris,pkg /home/glassfish/.org.opensolaris,pkg
 
-#change group of glassfish home directory to glassfishadm
-sudo chgrp -R glassfishadm /home/glassfish
+    #exit from glassfish user
+    #exit
 
-#just to make sure: change owner of glassfish home directory to glassfish
-sudo chown -R glassfish /home/glassfish
+    #change group of glassfish home directory to glassfishadm
+    sudo chgrp -R glassfishadm /home/glassfish
 
-#make sure the relevant files are executable/modifyable/readable for owner and group
-sudo chmod -R ug+rwx /home/glassfish/bin/
-sudo chmod -R ug+rwx /home/glassfish/glassfish/bin/
+    #just to make sure: change owner of glassfish home directory to glassfish
+    sudo chown -R glassfish /home/glassfish
 
-#others are not allowed to execute/modify/read them
-sudo chmod -R o-rwx /home/glassfish/bin/
-sudo chmod -R o-rwx /home/glassfish/glassfish/bin/
+    #make sure the relevant files are executable/modifyable/readable for owner and group
+    sudo chmod -R ug+rwx /home/glassfish/bin/
+    sudo chmod -R ug+rwx /home/glassfish/glassfish/bin/
+
+    #others are not allowed to execute/modify/read them
+    sudo chmod -R o-rwx /home/glassfish/bin/
+    sudo chmod -R o-rwx /home/glassfish/glassfish/bin/
+
+    return 0
+}
+
+case "$1" in
+    configure|triggered)
+        echo "postinst called with arguments: '$1', '$2'"
+        install_glassfish_user
+        install_java
+        install_glassfish
+    ;;
+
+    abort-upgrade|abort-remove|abort-deconfigure)
+        echo "postinst called with argument: '$1'"
+    ;;
+
+    *)
+    echo "postinst called with unknown argument '$1'" >&2
+    exit 0
+    ;;
+esac
+
+#DEBHELPER#
+
+exit 0
